/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BlogPost {
  'id' : string,
  'status' : ApprovalStatus,
  'title' : string,
  'content' : string,
  'coverImageId' : [] | [string],
  'tags' : Array<string>,
  'publishedAt' : Time,
  'author' : string,
}
export interface BlogPostInput {
  'title' : string,
  'content' : string,
  'coverImageId' : [] | [string],
  'tags' : Array<string>,
  'author' : string,
}
export interface BlogPostMetadata {
  'id' : string,
  'title' : string,
  'publishedAt' : Time,
  'author' : string,
}
export interface FileInput {
  'title' : string,
  'description' : string,
  'fileSize' : string,
  'fileType' : FileType,
  'version' : [] | [string],
  'category' : string,
  'fileUrl' : string,
}
export interface FilePost {
  'id' : string,
  'title' : string,
  'description' : string,
  'fileSize' : string,
  'fileType' : FileType,
  'version' : [] | [string],
  'category' : string,
  'uploadedAt' : Time,
  'fileUrl' : string,
}
export type FileType = { 'APK' : null } |
  { 'DOC' : null } |
  { 'EXE' : null } |
  { 'PDF' : null } |
  { 'TXT' : null } |
  { 'OTHER' : null };
export interface SiteConfiguration {
  'email' : string,
  'address' : string,
  'phone' : string,
  'socialMedia' : {
    'linkedin' : string,
    'twitter' : string,
    'instagram' : string,
    'whatsapp' : string,
    'facebook' : string,
    'youtube' : string,
  },
}
export interface Subscription {
  'id' : string,
  'subscribedAt' : Time,
  'email' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoInput {
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'description' : string,
  'videoUrl' : string,
}
export interface VideoPost {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'description' : string,
  'videoUrl' : string,
  'uploadedAt' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCalleeIceCandidate' : ActorMethod<[string, string], undefined>,
  'addCallerIceCandidate' : ActorMethod<[string, string], undefined>,
  'approveBlogPost' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAndPublishBlogPost' : ActorMethod<[BlogPostInput], string>,
  'createBlogPost' : ActorMethod<[BlogPostInput], string>,
  'createCallRoom' : ActorMethod<[string], undefined>,
  'createFile' : ActorMethod<[FileInput], string>,
  'createVideo' : ActorMethod<[VideoInput], string>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteCallRoom' : ActorMethod<[string], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteSubscription' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllBlogPostMetadata' : ActorMethod<[], Array<BlogPostMetadata>>,
  'getAllBlogPostsAdmin' : ActorMethod<[], Array<BlogPost>>,
  'getAllFiles' : ActorMethod<[], Array<FilePost>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAllVideos' : ActorMethod<[], Array<VideoPost>>,
  'getAnswer' : ActorMethod<[string], [] | [string]>,
  'getBlogPostById' : ActorMethod<[string], BlogPost>,
  'getBlogPostsByTag' : ActorMethod<[string], Array<BlogPostMetadata>>,
  'getCalleeIceCandidates' : ActorMethod<[string], Array<string>>,
  'getCallerIceCandidates' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOffer' : ActorMethod<[string], [] | [string]>,
  'getSiteConfiguration' : ActorMethod<[], SiteConfiguration>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectBlogPost' : ActorMethod<[string], undefined>,
  'roomExists' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAnswer' : ActorMethod<[string, string], undefined>,
  'setOffer' : ActorMethod<[string, string], undefined>,
  'subscribe' : ActorMethod<[string], string>,
  'updateBlogPost' : ActorMethod<[string, BlogPostInput], undefined>,
  'updateFile' : ActorMethod<[string, FileInput], undefined>,
  'updateSiteConfiguration' : ActorMethod<[SiteConfiguration], undefined>,
  'updateVideo' : ActorMethod<[string, VideoInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];