/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'coverImageId' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
});
export const FileType = IDL.Variant({
  'APK' : IDL.Null,
  'DOC' : IDL.Null,
  'EXE' : IDL.Null,
  'PDF' : IDL.Null,
  'TXT' : IDL.Null,
  'OTHER' : IDL.Null,
});
export const FileInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileSize' : IDL.Text,
  'fileType' : FileType,
  'version' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const VideoInput = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const BlogPostMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'publishedAt' : Time,
  'author' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'status' : ApprovalStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'coverImageId' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Time,
  'author' : IDL.Text,
});
export const FilePost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileSize' : IDL.Text,
  'fileType' : FileType,
  'version' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'uploadedAt' : Time,
  'fileUrl' : IDL.Text,
});
export const Subscription = IDL.Record({
  'id' : IDL.Text,
  'subscribedAt' : Time,
  'email' : IDL.Text,
});
export const VideoPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteConfiguration = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'socialMedia' : IDL.Record({
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'whatsapp' : IDL.Text,
    'facebook' : IDL.Text,
    'youtube' : IDL.Text,
  }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCalleeIceCandidate' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addCallerIceCandidate' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveBlogPost' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAndPublishBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
  'createBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
  'createCallRoom' : IDL.Func([IDL.Text], [], []),
  'createFile' : IDL.Func([FileInput], [IDL.Text], []),
  'createVideo' : IDL.Func([VideoInput], [IDL.Text], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteCallRoom' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteSubscription' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPostMetadata' : IDL.Func(
      [],
      [IDL.Vec(BlogPostMetadata)],
      ['query'],
    ),
  'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FilePost)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
  'getAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getBlogPostsByTag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPostMetadata)],
      ['query'],
    ),
  'getCalleeIceCandidates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerIceCandidates' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSiteConfiguration' : IDL.Func([], [SiteConfiguration], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectBlogPost' : IDL.Func([IDL.Text], [], []),
  'roomExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setOffer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'subscribe' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [], []),
  'updateFile' : IDL.Func([IDL.Text, FileInput], [], []),
  'updateSiteConfiguration' : IDL.Func([SiteConfiguration], [], []),
  'updateVideo' : IDL.Func([IDL.Text, VideoInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'coverImageId' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
  });
  const FileType = IDL.Variant({
    'APK' : IDL.Null,
    'DOC' : IDL.Null,
    'EXE' : IDL.Null,
    'PDF' : IDL.Null,
    'TXT' : IDL.Null,
    'OTHER' : IDL.Null,
  });
  const FileInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileSize' : IDL.Text,
    'fileType' : FileType,
    'version' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const VideoInput = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const BlogPostMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'publishedAt' : Time,
    'author' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'status' : ApprovalStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'coverImageId' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Time,
    'author' : IDL.Text,
  });
  const FilePost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileSize' : IDL.Text,
    'fileType' : FileType,
    'version' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'uploadedAt' : Time,
    'fileUrl' : IDL.Text,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Text,
    'subscribedAt' : Time,
    'email' : IDL.Text,
  });
  const VideoPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteConfiguration = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'socialMedia' : IDL.Record({
      'linkedin' : IDL.Text,
      'twitter' : IDL.Text,
      'instagram' : IDL.Text,
      'whatsapp' : IDL.Text,
      'facebook' : IDL.Text,
      'youtube' : IDL.Text,
    }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCalleeIceCandidate' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addCallerIceCandidate' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveBlogPost' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAndPublishBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
    'createBlogPost' : IDL.Func([BlogPostInput], [IDL.Text], []),
    'createCallRoom' : IDL.Func([IDL.Text], [], []),
    'createFile' : IDL.Func([FileInput], [IDL.Text], []),
    'createVideo' : IDL.Func([VideoInput], [IDL.Text], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteCallRoom' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteSubscription' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPostMetadata' : IDL.Func(
        [],
        [IDL.Vec(BlogPostMetadata)],
        ['query'],
      ),
    'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FilePost)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoPost)], ['query']),
    'getAnswer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getBlogPostsByTag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPostMetadata)],
        ['query'],
      ),
    'getCalleeIceCandidates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerIceCandidates' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOffer' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSiteConfiguration' : IDL.Func([], [SiteConfiguration], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectBlogPost' : IDL.Func([IDL.Text], [], []),
    'roomExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setOffer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'subscribe' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPostInput], [], []),
    'updateFile' : IDL.Func([IDL.Text, FileInput], [], []),
    'updateSiteConfiguration' : IDL.Func([SiteConfiguration], [], []),
    'updateVideo' : IDL.Func([IDL.Text, VideoInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };