/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface VideoInput {
    title: string;
    thumbnailUrl?: string;
    description: string;
    videoUrl: string;
}
export interface BlogPost {
    id: string;
    status: ApprovalStatus;
    title: string;
    content: string;
    coverImageId?: string;
    tags: Array<string>;
    publishedAt: Time;
    author: string;
}
export type Time = bigint;
export interface FileInput {
    title: string;
    description: string;
    fileSize: string;
    fileType: FileType;
    version?: string;
    category: string;
    fileUrl: string;
}
export interface BlogPostInput {
    title: string;
    content: string;
    coverImageId?: string;
    tags: Array<string>;
    author: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BlogPostMetadata {
    id: string;
    title: string;
    publishedAt: Time;
    author: string;
}
export interface Subscription {
    id: string;
    subscribedAt: Time;
    email: string;
}
export interface FilePost {
    id: string;
    title: string;
    description: string;
    fileSize: string;
    fileType: FileType;
    version?: string;
    category: string;
    uploadedAt: Time;
    fileUrl: string;
}
export interface SiteConfiguration {
    email: string;
    address: string;
    phone: string;
    socialMedia: {
        linkedin: string;
        twitter: string;
        instagram: string;
        whatsapp: string;
        facebook: string;
        youtube: string;
    };
}
export interface VideoPost {
    id: string;
    title: string;
    thumbnailUrl?: string;
    description: string;
    videoUrl: string;
    uploadedAt: Time;
}
export interface UserProfile {
    name: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum FileType {
    APK = "APK",
    DOC = "DOC",
    EXE = "EXE",
    PDF = "PDF",
    TXT = "TXT",
    OTHER = "OTHER"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCalleeIceCandidate(code: string, candidate: string): Promise<void>;
    addCallerIceCandidate(code: string, candidate: string): Promise<void>;
    approveBlogPost(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAndPublishBlogPost(input: BlogPostInput): Promise<string>;
    createBlogPost(input: BlogPostInput): Promise<string>;
    createCallRoom(code: string): Promise<void>;
    createFile(input: FileInput): Promise<string>;
    createVideo(input: VideoInput): Promise<string>;
    deleteBlogPost(id: string): Promise<void>;
    deleteCallRoom(code: string): Promise<void>;
    deleteFile(id: string): Promise<void>;
    deleteSubscription(id: string): Promise<void>;
    deleteVideo(id: string): Promise<void>;
    getAllBlogPostMetadata(): Promise<Array<BlogPostMetadata>>;
    getAllBlogPostsAdmin(): Promise<Array<BlogPost>>;
    getAllFiles(): Promise<Array<FilePost>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAllVideos(): Promise<Array<VideoPost>>;
    getAnswer(code: string): Promise<string | null>;
    getBlogPostById(id: string): Promise<BlogPost>;
    getBlogPostsByTag(tag: string): Promise<Array<BlogPostMetadata>>;
    getCalleeIceCandidates(code: string): Promise<Array<string>>;
    getCallerIceCandidates(code: string): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOffer(code: string): Promise<string | null>;
    getSiteConfiguration(): Promise<SiteConfiguration>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectBlogPost(id: string): Promise<void>;
    roomExists(code: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAnswer(code: string, sdp: string): Promise<void>;
    setOffer(code: string, sdp: string): Promise<void>;
    subscribe(email: string): Promise<string>;
    updateBlogPost(id: string, input: BlogPostInput): Promise<void>;
    updateFile(id: string, input: FileInput): Promise<void>;
    updateSiteConfiguration(config: SiteConfiguration): Promise<void>;
    updateVideo(id: string, input: VideoInput): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, BlogPost as _BlogPost, BlogPostInput as _BlogPostInput, FileInput as _FileInput, FilePost as _FilePost, FileType as _FileType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoInput as _VideoInput, VideoPost as _VideoPost, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCalleeIceCandidate(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalleeIceCandidate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalleeIceCandidate(arg0, arg1);
            return result;
        }
    }
    async addCallerIceCandidate(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallerIceCandidate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallerIceCandidate(arg0, arg1);
            return result;
        }
    }
    async approveBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBlogPost(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAndPublishBlogPost(arg0: BlogPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAndPublishBlogPost(to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAndPublishBlogPost(to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createBlogPost(arg0: BlogPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCallRoom(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCallRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCallRoom(arg0);
            return result;
        }
    }
    async createFile(arg0: FileInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFile(to_candid_FileInput_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFile(to_candid_FileInput_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVideo(arg0: VideoInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(to_candid_VideoInput_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(to_candid_VideoInput_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteCallRoom(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallRoom(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteSubscription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubscription(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getAllBlogPostMetadata(): Promise<Array<BlogPostMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostMetadata();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostMetadata();
            return result;
        }
    }
    async getAllBlogPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostsAdmin();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostsAdmin();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFiles(): Promise<Array<FilePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return result;
        }
    }
    async getAllVideos(): Promise<Array<VideoPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideos();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideos();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnswer(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnswer(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnswer(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostById(arg0: string): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return from_candid_BlogPost_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return from_candid_BlogPost_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByTag(arg0: string): Promise<Array<BlogPostMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByTag(arg0);
            return result;
        }
    }
    async getCalleeIceCandidates(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalleeIceCandidates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalleeIceCandidates(arg0);
            return result;
        }
    }
    async getCallerIceCandidates(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIceCandidates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIceCandidates(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffer(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffer(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffer(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteConfiguration(): Promise<SiteConfiguration> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteConfiguration();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBlogPost(arg0);
            return result;
        }
    }
    async roomExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.roomExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.roomExists(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAnswer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnswer(arg0, arg1);
            return result;
        }
    }
    async setOffer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOffer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOffer(arg0, arg1);
            return result;
        }
    }
    async subscribe(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: BlogPostInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, to_candid_BlogPostInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFile(arg0: string, arg1: FileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFile(arg0, to_candid_FileInput_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFile(arg0, to_candid_FileInput_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSiteConfiguration(arg0: SiteConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteConfiguration(arg0);
            return result;
        }
    }
    async updateVideo(arg0: string, arg1: VideoInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, to_candid_VideoInput_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, to_candid_VideoInput_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPost_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FilePost_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilePost): FilePost {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_VideoPost_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoPost): VideoPost {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ApprovalStatus;
    title: string;
    content: string;
    coverImageId: [] | [string];
    tags: Array<string>;
    publishedAt: _Time;
    author: string;
}): {
    id: string;
    status: ApprovalStatus;
    title: string;
    content: string;
    coverImageId?: string;
    tags: Array<string>;
    publishedAt: Time;
    author: string;
} {
    return {
        id: value.id,
        status: from_candid_ApprovalStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        coverImageId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.coverImageId)),
        tags: value.tags,
        publishedAt: value.publishedAt,
        author: value.author
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    fileSize: string;
    fileType: _FileType;
    version: [] | [string];
    category: string;
    uploadedAt: _Time;
    fileUrl: string;
}): {
    id: string;
    title: string;
    description: string;
    fileSize: string;
    fileType: FileType;
    version?: string;
    category: string;
    uploadedAt: Time;
    fileUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        fileSize: value.fileSize,
        fileType: from_candid_FileType_n27(_uploadFile, _downloadFile, value.fileType),
        version: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.version)),
        category: value.category,
        uploadedAt: value.uploadedAt,
        fileUrl: value.fileUrl
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnailUrl: [] | [string];
    description: string;
    videoUrl: string;
    uploadedAt: _Time;
}): {
    id: string;
    title: string;
    thumbnailUrl?: string;
    description: string;
    videoUrl: string;
    uploadedAt: Time;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.thumbnailUrl)),
        description: value.description,
        videoUrl: value.videoUrl,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    APK: null;
} | {
    DOC: null;
} | {
    EXE: null;
} | {
    PDF: null;
} | {
    TXT: null;
} | {
    OTHER: null;
}): FileType {
    return "APK" in value ? FileType.APK : "DOC" in value ? FileType.DOC : "EXE" in value ? FileType.EXE : "PDF" in value ? FileType.PDF : "TXT" in value ? FileType.TXT : "OTHER" in value ? FileType.OTHER : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FilePost>): Array<FilePost> {
    return value.map((x)=>from_candid_FilePost_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoPost>): Array<VideoPost> {
    return value.map((x)=>from_candid_VideoPost_n30(_uploadFile, _downloadFile, x));
}
function to_candid_BlogPostInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostInput): _BlogPostInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_FileInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileInput): _FileInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FileType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoInput): _VideoInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    coverImageId?: string;
    tags: Array<string>;
    author: string;
}): {
    title: string;
    content: string;
    coverImageId: [] | [string];
    tags: Array<string>;
    author: string;
} {
    return {
        title: value.title,
        content: value.content,
        coverImageId: value.coverImageId ? candid_some(value.coverImageId) : candid_none(),
        tags: value.tags,
        author: value.author
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    fileSize: string;
    fileType: FileType;
    version?: string;
    category: string;
    fileUrl: string;
}): {
    title: string;
    description: string;
    fileSize: string;
    fileType: _FileType;
    version: [] | [string];
    category: string;
    fileUrl: string;
} {
    return {
        title: value.title,
        description: value.description,
        fileSize: value.fileSize,
        fileType: to_candid_FileType_n14(_uploadFile, _downloadFile, value.fileType),
        version: value.version ? candid_some(value.version) : candid_none(),
        category: value.category,
        fileUrl: value.fileUrl
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    thumbnailUrl?: string;
    description: string;
    videoUrl: string;
}): {
    title: string;
    thumbnailUrl: [] | [string];
    description: string;
    videoUrl: string;
} {
    return {
        title: value.title,
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        description: value.description,
        videoUrl: value.videoUrl
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    APK: null;
} | {
    DOC: null;
} | {
    EXE: null;
} | {
    PDF: null;
} | {
    TXT: null;
} | {
    OTHER: null;
} {
    return value == FileType.APK ? {
        APK: null
    } : value == FileType.DOC ? {
        DOC: null
    } : value == FileType.EXE ? {
        EXE: null
    } : value == FileType.PDF ? {
        PDF: null
    } : value == FileType.TXT ? {
        TXT: null
    } : value == FileType.OTHER ? {
        OTHER: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
